version: '3'

services:

  mongo-client:
    build: .
    image: py-mongo
    container_name: py-mongo-demo 


  mongo-test:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data-volume:/data/db
  

volumes:
  mongo-data-volume:
    driver: local